import fs from 'node:fs';

const rgba = (r,g,b,a=1) => `rgba(${r}, ${g}, ${b}, ${a})`;
const recipe = (dominant, secondary, materialClass) => ({
  dominantAlbedo:dominant, secondaryAlbedo:secondary, materialClass,
  materialClassConfidence:.82, colorGradient:{type:'radial',stops:[{position:0,color:dominant},{position:1,color:secondary}]}
});
const action = (role, pivot=[0,0,0]) => ({
  animationRole:role, pivot:{mode:'local',localPosition:pivot,axis:[0,1,0],confidence:.8},
  transformChannels:{translate:true,rotate:true,scale:true,bend:false,twist:false,detach:false,visibility:true,materialState:true},
  sockets:[], collider:{type:'box',offset:[0,0,0],scale:[1,1,1],isTrigger:true}, destruction:{breakable:false,fractureGroup:role,seamRefs:[],detachableFragments:[],breakImpulse:0,debrisMaterial:'brass'}
});
const comp = (id,name,parent,level,primitive,material,dimensions,position,features=[],attachment=null) => ({
  id,name,parent,level,role:'part',importance:level==='macro'?1:.75,confidence:.82,primitive,topologyClass:'assembled-solid',topologyRationale:'Separate named solid part matching the loupe assembly.',
  geometryDescriptor:{topologyIntent:'low-poly beveled solid',edgeTreatment:{type:'chamfer',bevelRadius:.025,segments:3},deformationStack:[],uvStrategy:'generated procedural coordinates',normalStrategy:'vertex normals from generated geometry'},
  attachment,dimensions:{width:dimensions[0],height:dimensions[1],depth:dimensions[2],units:'scene',confidence:.8},transform:{position,rotation:[0,0,0],scale:[1,1,1]},actionProfile:action(level==='macro'?'assembly-root':'static-part',position),material,materialLayers:[material],colorMaterialRecipe:recipe(material==='glass'?rgba(220,234,240,.7):material==='wood'?rgba(112,67,41):rgba(185,130,63),material==='glass'?rgba(167,193,199,.5):material==='wood'?rgba(63,37,28):rgba(111,71,41),material==='glass'?'glass':material==='wood'?'wood':'metal'),localFeatures:features,evidenceRefs:['full-object'],surfaceDetail:{macroRoughness:.3,mesoRoughness:.18,microRoughness:.08,bumpAmplitude:material==='wood'?.04:.015,normalPattern:material==='wood'?'vertical grain':'fine satin microtexture',displacementPattern:'none',occlusionPattern:'cavity darkening',notes:'Procedural low-contrast finish.'}
});

const feature = (id,kind,description,component) => ({id,kind,description,region:{x:0,y:0,width:1,height:1,units:'normalized'},scale:'object-relative',affects:'geometry/material',mapsTo:{type:'component.localFeatures',ref:component},evidenceRef:'full-object',confidence:.8});
const components = [
  comp('lensAssembly','Lens assembly',null,'macro','cylinder','glass',[1.16,.18,1.16],[0,0,0],[feature('lens-bezel','bevel','Concentric thick rim and inner glass seating edge','lensAssembly')]),
  comp('brassOuterBezel','Outer brass bezel','lensAssembly','meso','torus','brass',[1.2,.16,1.2],[0,.13,0],[feature('rim-step','ridge','Raised outer brass ring with stepped inner band','brassOuterBezel')],{parentSocket:'lensAssembly',localStart:[0,.1,0],localEnd:[0,.16,0],contactType:'overlap',overlap:.03,gapTolerance:.02,evidenceRefs:['full-object']}),
  comp('lensGlass','Glass lens','lensAssembly','meso','cylinder','glass',[1.06,.06,1.06],[0,.095,0],[feature('glass-highlight','gloss','Pale transparent lens with soft low-roughness highlight','lensGlass')],{parentSocket:'lensAssembly',localStart:[0,.06,0],localEnd:[0,.12,0],contactType:'seat',overlap:.025,gapTolerance:.02,evidenceRefs:['full-object']}),
  comp('connector','Connector neck',null,'macro','cylinder','brass',[.38,.22,.38],[0,.08,.52],[feature('connector-rings','ridge','Two stepped collar rings at bezel-to-handle joint','connector')],{parentSocket:'lensAssembly',localStart:[-.38,.08,.42],localEnd:[-.52,.08,.62],contactType:'butt',overlap:.04,gapTolerance:.02,evidenceRefs:['full-object']}),
  comp('handle','Wood grip',null,'macro','tapered-sweep','wood',[.54,1.55,.54],[-.95,.09,.92],[feature('grip-ridges','ridge','Repeated longitudinal grip ridges','handle'),feature('wood-bevel','bevel','Rounded grip and pommel edges','handle')],{parentSocket:'connector',localStart:[-.52,.08,.62],localEnd:[-1.95,.08,1.42],contactType:'overlap',overlap:.05,gapTolerance:.02,evidenceRefs:['full-object']}),
  comp('pommel','Pommel cap','handle','meso','cylinder','wood',[.58,.28,.58],[-1.98,.09,1.44],[feature('pommel-band','ridge','Dark end cap with brass band','pommel')],{parentSocket:'handle',localStart:[-1.9,.09,1.4],localEnd:[-2.08,.09,1.5],contactType:'overlap',overlap:.04,gapTolerance:.02,evidenceRefs:['full-object']})
];
const spec = {
  targetName:'Vintage handheld loupe', targetId:'loupe', schemaVersion:'2.1', sourceImage:'loupe-preview/loupe-reference.png', suitability:'pass', terminologyProfile:{domain:'real-time procedural Three.js asset',geometryTerms:['cylinder','torus','taper','bevel','surface normal'],materialTerms:['albedo','roughness','metalness','transmission','normal'],lightingTerms:['key light','fill light','contact shadow']}, scores:{object_isolation:3,silhouette_readability:3,depth_inference:2,primitive_decomposition:3,material_procedurality:3,occlusion_risk:1,interaction_fit:3},
  preSpecAssessment:{objectClass:{primaryType:'handheld magnifying loupe',primaryDomain:'object',formLanguage:['hard-surface','radial','compound'],structureKind:['layered shell','articulated-ready assembly'],motionPotential:['static prop','whole-object transform','lens tilt'],materialFamilies:['metal','wood','glass'],notes:'Single-view procedural approximation.'},complexity:{tier:'moderate',scores:{silhouetteComplexity:2,componentCount:2,hierarchyDepth:2,repetitionDensity:1,materialLayerCount:2,localDetailDensity:2,occlusionRisk:1,actionReadinessNeed:2},estimatedCounts:{macroComponents:3,mesoComponents:3,microFeatureGroups:2,materialLayers:3,repetitionSystems:1}},specDepthDecision:{requiredDepth:'moderate',minimumComponentLevels:['macro','meso'],needsRepetitionSystems:true,needsMaterialLocalOverrides:true,needsMultipleReviewViews:true,needsActionReadyHierarchy:true},detailInventory:{scanMethod:'component-zones',targetMinDetails:6,details:[]},unknownsToResolveBeforeImplementation:[]},
  qualityContract:{qualityBar:'moderate',definitionOfDone:['Recognizable loupe silhouette with circular glass, thick brass bezel, diagonal wood grip and seated tabletop placement.'],minimumSpecDepth:{macroComponents:2,mesoComponents:3,microFeatureGroups:2,materialLayers:2,repetitionSystems:1,reviewViewpoints:3},featureGroups:[{id:'silhouette',name:'Lens and handle silhouette',required:true,qualityCriteria:['Circular lens and diagonal tapered handle remain legible from front and three-quarter views.']},{id:'materials',name:'Brass wood glass material zones',required:true,qualityCriteria:['Brass, wood and glass have distinct PBR response under warm key light.']},{id:'placement',name:'Tabletop contact and orientation',required:true,qualityCriteria:['Lowest geometry seats on the desk surface without floating or penetrating the newspaper.']}],visualDeltaChecks:['lens-to-handle proportion','bezel thickness','wood grip ridges','tabletop contact']},
  qualityTargets:{targetFidelity:.72,mustMatch:['macro silhouette and component hierarchy','brass/wood/glass material response','tabletop horizontal placement'],niceToHave:['micro patina','exact optical curvature'],fpsTarget:60,reviewViewpoints:['front','top','three-quarter','side']},
  featureReviewTargets:[{id:'loupe-silhouette',name:'Lens and handle silhouette',tier:'critical',passIds:['blockout','form-refinement'],minimumScore:.8,mustPass:true,componentRefs:['lensAssembly','handle'],evidenceRefs:['full-object']},{id:'material-zones',name:'Brass wood glass material zones',tier:'critical',passIds:['material-pass'],minimumScore:.75,mustPass:true,componentRefs:['brassOuterBezel','handle','lensGlass'],evidenceRefs:['full-object']}],
  coordinateFrame:{front:'+Z',up:'+Y',origin:'lens center',surface:'tabletop-horizontal',units:'scene'}, silhouette:{boundingShape:'circular lens with diagonal tapered handle',aspectRatios:[2.22,1.48,.18],symmetry:'radial lens / asymmetric handle',dominantCurves:['bezel circles','rounded pommel'],negativeSpaces:['inner lens aperture'],landmarks:['outer bezel','connector neck','grip ridges']},
  componentTree:components,
  materials:[{id:'brass',name:'Satin brass',type:'physical',baseColor:'#B9823F',colorVariation:{palette:['#B9823F','#6F4729','#D5A45B'],pattern:'low-contrast patina at cavities',amplitude:.12},roughness:{base:.32,variation:.12,map:'procedural-independent-roughness'},metalness:{base:.72,variation:.06},normal:{pattern:'fine satin microtexture',strength:.12,scale:48},ambientOcclusion:{cavityStrength:.3,contactShadowBias:.25},localOverrides:[{id:'bezel-cavity',region:'inner ring',roughness:.44,color:'#6F4729',evidenceRefs:['full-object']}]},{id:'wood',name:'Warm carved wood',type:'standard',baseColor:'#704329',colorVariation:{palette:['#704329','#3F251C','#9B633C'],pattern:'vertical longitudinal grain',amplitude:.18},roughness:{base:.78,variation:.1,map:'procedural-independent-roughness'},metalness:{base:0,variation:0},normal:{pattern:'longitudinal grip ridges',strength:.28,scale:24},ambientOcclusion:{cavityStrength:.28,contactShadowBias:.3},localOverrides:[{id:'grip-grooves',region:'handle sides',roughness:.86,color:'#3F251C',evidenceRefs:['full-object']}]},{id:'glass',name:'Pale transparent glass',type:'physical',baseColor:'#DCEAF0',colorVariation:{palette:['#DCEAF0','#A7C1C7'],pattern:'subtle edge tint',amplitude:.06},roughness:{base:.16,variation:.04,map:'procedural-independent-roughness'},metalness:{base:0,variation:0},normal:{pattern:'none',strength:.02,scale:8},ambientOcclusion:{cavityStrength:.12,contactShadowBias:.2},localOverrides:[{id:'glass-edge',region:'lens perimeter',roughness:.2,color:'#A7C1C7',evidenceRefs:['full-object']}]}],
  repetitionSystems:[{id:'grip-ridges',componentRef:'handle',distribution:'linear',count:9,spacing:.16,primitive:'torus',material:'brass',evidenceRefs:['full-object']}], lightingFromPhoto:['key light: large soft source from upper-left; warm neutral exposure and ACES tone mapping','fill light: low-intensity neutral environment','contact shadow: soft tabletop grounding below lens and handle'], proceduralStrategy:['Use torus and cylinder primitives for the radial lens and collars.','Use a tapered cylinder with repeated torus ridges for the wood handle.','Keep lens, connector and handle as independent pivots for later tabletop animation.'], buildPasses:[{id:'blockout',componentRefs:['lensAssembly','handle']},{id:'structural-pass',componentRefs:['brassOuterBezel','lensGlass','connector','pommel']},{id:'form-refinement',componentRefs:['handle','connector']},{id:'material-pass',componentRefs:['brass','wood','glass']},{id:'interaction-pass',componentRefs:['lensAssembly','handle']}], actionReadiness:{contract:'Named pivots, collider proxy and transform channels are provided for each movable assembly.',defaultRigType:'action-ready-static-rig'}, selfCorrectLoop:{enabled:true,visualAcceptance:{reviewer:'ai-vision',threshold:.7,comparisonArtifactRequired:false,featureReviewPolicy:{enabled:true,reviewUnit:'semantic-subsystem',maxCriticalFeaturesPerPass:3,maxImportantFeaturesPerPass:2,criticalDefaultThreshold:.8,importantAverageThreshold:.65}}}, sculptPipeline:{passGateMode:'locked-sequential',passOrder:['blockout','structural-pass','form-refinement','material-pass','interaction-pass'],currentPass:'blockout',completedPasses:[]}, lookDevTargets:{qualityPriority:'runtime-performance',materialPass:{albedoPaletteRequired:true,roughnessVariationRequired:true,normalOrBumpRequired:true,localOverridesRequired:true}}, animationAnchors:['root supports tabletop translation/rotation','lensAssembly supports future tilt'], risks:[], performanceBudget:{qualityPriority:'runtime-performance',targetTriangles:12000,maxDrawCalls:40,textureSize:1024,fpsTarget:60,optimizationPolicy:'share materials and keep segments moderate'}, viewEvidence:[{id:'full-object',view:'primary',imageRegion:{x:0,y:0,width:1,height:1,units:'normalized'},observations:['circular lens','thick brass rim','diagonal wood handle'],confidence:.9}]
};
spec.preSpecAssessment.detailInventory.details = [feature('bezel-rim','ridge','Concentric outer and inner brass rings','brassOuterBezel'),feature('glass-highlight','gloss','Low-roughness pale glass face','lensGlass'),feature('connector-collars','ridge','Stepped connector collars','connector'),feature('grip-ridges','ridge','Repeated longitudinal grip ridges','handle'),feature('wood-bevel','bevel','Rounded grip and pommel edges','handle'),feature('pommel-band','ridge','Brass-banded end cap','pommel')];
fs.writeFileSync('loupe-preview/object-sculpt-spec.json', JSON.stringify(spec,null,2));
