import fs from 'node:fs';

const file = new URL('./object-sculpt-spec.json', import.meta.url);
const spec = JSON.parse(fs.readFileSync(file, 'utf8'));
spec.targetName = 'roomShell';
spec.targetId = 'roomShell';
spec.suitability = 'pass';
spec.coordinateFrame = { upAxis: '+Y', frontAxis: '+Z', origin: 'base center at y=0', units: 'scene units' };
spec.silhouette.proportions.wallThickness = 1;
spec.silhouette = { primary: 'open three-wall miniature shell', proportions: { width: 20, depth: 15.3, height: 15.3 }, negativeSpaces: ['open front', 'open top', 'front base recess', 'left wall window opening'], symmetry: 'flat rear roof rail with left raised sign and asymmetric base' };
spec.assumptions = [
  'Rear and underside surfaces are continuous solid approximations because the reference views do not expose construction joinery.',
  'The left-wall window is a true opening through the 1.0-unit wall with aligned inner and outer frames; right-door hardware and hidden joinery remain simplified, replaceable architectural details based on the supplied detail views.',
];
spec.preSpecAssessment.objectClass = {
  primaryType: 'open miniature architectural room shell', primaryDomain: 'object',
  formLanguage: ['hard-surface', 'architectural', 'layered shell'],
  structureKind: ['continuous wall solids', 'stepped profile', 'extruded polygon base'],
  motionPotential: ['static prop', 'whole-object transform'], materialFamilies: ['painted plaster', 'wood trim', 'painted door', 'metal grille'],
  confidence: 0.91, notes: 'Three orthographic/near-orthographic reference groups provide macro proportions and two wall detail views.'
};
spec.preSpecAssessment.complexity = { tier: 'moderate', scores: { silhouetteComplexity: 3, componentCount: 3, hierarchyDepth: 3, repetitionDensity: 2, materialLayerCount: 3, localDetailDensity: 3, occlusionRisk: 3, actionReadinessNeed: 1 }, estimatedCounts: { macroComponents: 5, mesoComponents: 12, microFeatureGroups: 6, materialLayers: 4, repetitionSystems: 3 }, reasoning: ['Three perpendicular walls, stepped roof trims, a connected raised sign, a real door opening, and an asymmetric extruded base footprint.'] };
spec.preSpecAssessment.specDepthDecision = { requiredDepth: 'moderate', minimumComponentLevels: ['macro', 'meso', 'micro'], needsRepetitionSystems: true, needsMaterialLocalOverrides: true, needsMultipleReviewViews: true, needsActionReadyHierarchy: true, rationale: 'Architectural shell has repeated trim members and checker steps plus multiple replaceable signs and openings.' };
const detail = (id, kind, ref, scale = 'meso') => ({ id, kind, description: id, region: { x: 0, y: 0, width: 1, height: 1, units: 'normalized' }, scale, affects: kind === 'decal' ? 'material' : 'geometry', mapsTo: { type: 'component.localFeatures', ref }, evidenceRef: 'full-object', confidence: 0.86 });
spec.preSpecAssessment.detailInventory = { scanMethod: 'multi-reference semantic inventory', targetMinDetails: 10, note: 'Each identity feature is mapped to a named component.', details: [detail('stepped-roof-profile', 'contour', 'backWall'), detail('left-raised-sign', 'contour', 'leftRaisedSign'), detail('sign-window', 'hole', 'signWindow'), detail('left-window', 'hole', 'leftWindow'), detail('left-window-texture-panel', 'decal', 'leftWindowTexturePanel'), detail('embedded-door', 'ridge', 'door'), detail('checker-steps', 'ridge', 'doorSteps'), detail('front-base-recess', 'hole', 'baseTrim'), detail('right-plaque', 'decal', 'rightLongPlaque'), detail('left-plaque', 'decal', 'leftPlaque'), detail('wall-thickness', 'contour', 'backWall'), detail('floor-plank-lines', 'contour', 'baseFloor')] };
function component(id, name, level, role, parent, dims, material, features = []) {
  const rgba = material === 'wall' ? 'rgba(232, 223, 207, 1.0)' : material === 'door' ? 'rgba(81, 65, 138, 1.0)' : 'rgba(99, 56, 44, 1.0)';
  return { id, name, level, role, importance: level === 'macro' ? 0.95 : 0.78, confidence: 0.86, primitive: 'extrude', topologyClass: 'assembled-solid', topologyRationale: 'Architectural component uses a continuous extruded or beveled solid.', geometryDescriptor: { topologyIntent: 'continuous hard-surface solid', edgeTreatment: { type: 'chamfer', bevelRadius: level === 'macro' ? 0.12 : 0.06, segments: level === 'macro' ? 5 : 3 }, deformationStack: [], uvStrategy: 'generated procedural coordinates', normalStrategy: 'smooth vertex normals' }, parent, attachment: { parentSocket: `${parent}-socket`, localStart: [0, 0, 0], localEnd: [0, 0, 0], contactType: 'butt', embedDepth: 0.04, gapTolerance: 0.03 }, dimensions: { ...dims, units: 'scene', confidence: 0.86 }, transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] }, actionProfile: { animationRole: 'static-part', pivot: { mode: 'local', localPosition: [0, 0, 0], axis: [0, 1, 0], confidence: 0.85 }, transformChannels: { translate: true, rotate: true, scale: true, bend: false, twist: false, detach: false, visibility: true, materialState: true }, sockets: [], collider: { type: 'box', offset: [0, 0, 0], scale: [1, 1, 1], isTrigger: false, notes: '' }, constraints: [], destruction: { breakable: false, fractureGroup: id, seamRefs: [], detachableFragments: [], breakImpulse: 0, debrisMaterial: material } }, material, materialLayers: [material], deformations: [], joints: [], seams: [], localFeatures: features.map((x) => ({ id: x, kind: 'identity-feature', evidenceRefs: ['full-object'] })), surfaceDetail: { macroRoughness: 0.08, microRoughness: 0.06, bumpAmplitude: 0.02, normalPattern: 'subtle plaster or wood grain', displacementPattern: 'none', occlusionPattern: 'wall and trim contact', edgeWearPattern: 'soft bevel highlight', notes: 'Stylized matte miniature response.' }, evidenceRefs: ['full-object'], details: features, fidelityTier: 'form', colorMaterialRecipe: { dominantAlbedo: rgba, secondaryAlbedo: rgba, materialClass: ['wall', 'wallSide'].includes(material) ? 'ceramic' : material === 'iron' ? 'metal' : 'wood', materialClassConfidence: 0.8, baseColor: rgba, finish: 'matte', roughness: material === 'wall' ? 0.88 : 0.84, metalness: material === 'iron' ? 0.55 : 0 } };
}
const root = spec.componentTree?.[0] || { id: 'roomShell', name: 'roomShell' };
root.id = 'roomShell'; root.name = 'roomShell'; root.level = 'macro'; root.role = 'complete open shell'; root.material = 'wall'; root.materialLayers = ['wall', 'wood', 'floor', 'door']; root.dimensions = { width: 20, depth: 15.3, height: 15.3, units: 'scene' }; root.geometryDescriptor = { topologyIntent: 'continuous three-wall shell with extruded polygon base', edgeTreatment: { type: 'chamfer', bevelRadius: 0.12, segments: 5 }, deformationStack: [], uvStrategy: 'generated procedural coordinates', normalStrategy: 'smooth vertex normals' }; root.localFeatures = [{ id: 'open-front', kind: 'negative-space', evidenceRefs: ['full-object'] }, { id: 'open-top', kind: 'negative-space', evidenceRefs: ['full-object'] }]; root.colorMaterialRecipe = { dominantAlbedo: 'rgba(232, 223, 207, 1.0)', secondaryAlbedo: 'rgba(222, 212, 194, 1.0)', materialClass: 'ceramic', materialClassConfidence: 0.86, baseColor: 'rgba(232, 223, 207, 1.0)', finish: 'matte', roughness: 0.88, metalness: 0 };
spec.componentTree = [root,
  component('backWall', 'backWall', 'macro', 'continuous flat-top rear wall', 'roomShell', { width: 20, height: 12.9, depth: 1 }, 'wall', ['flat-rear-top', 'wall-thickness']),
  component('leftWall', 'leftWall', 'macro', 'open short wall with true window opening', 'roomShell', { width: 1, height: 12.48, depth: 6.3 }, 'wallSide', ['left-window', 'left-window-opening', 'inner-outer-window-frames', 'wall-thickness']),
  component('rightWall', 'rightWall', 'macro', 'short door wall with real opening', 'roomShell', { width: 1, height: 12.35, depth: 12.6 }, 'wall', ['embedded-door', 'wall-thickness']),
  component('baseFloor', 'baseFloor', 'macro', 'continuous floor polygon', 'roomShell', { width: 19.36, height: 0.4, depth: 14.14 }, 'floor', ['front-base-recess']),
  component('floorPlankLines', 'floorPlankLines', 'micro', 'subtle light floor plank seams', 'baseFloor', { width: 18.5, height: 0.02, depth: 12.0 }, 'floor', ['plank-line-pattern']),
  component('baseTrim', 'baseTrim', 'macro', 'thick stepped base and edge rails', 'roomShell', { width: 20, height: 0.95, depth: 14.85 }, 'base', ['front-base-recess']),
  component('roofTrim', 'roofTrim', 'meso', 'attached continuous flat rear roof rail', 'backWall', { width: 20.15, height: 0.42, depth: 0.72 }, 'wood', ['flat-rear-top']),
  component('leftRaisedSign', 'leftRaisedSign', 'meso', 'connected enlarged rounded sign extension', 'backWall', { width: 6.7, height: 2.2, depth: 1.55 }, 'woodLight', ['left-raised-sign']),
  component('signWindow', 'signWindow', 'micro', 'framed sign window with dark background and replaceable front logo texture', 'leftRaisedSign', { width: 4.55, height: 1.2, depth: 0.22 }, 'iron', ['sign-window', 'dark-background', 'cross-decorations-hidden', 'front-logo-texture', 'contain-fit', 'horizontal-orientation']),
  component('signWindow-frontTexture', 'signWindow-frontTexture', 'micro', 'replaceable transparent front logo plane over dark sign background', 'signWindow', { width: 3.74, height: 0.845, depth: 0.01 }, 'plaque', ['front-logo-texture', 'preserve-aspect', 'no-mirror']),
  component('leftPlaque', 'leftPlaque', 'micro', 'small sign plaque', 'leftRaisedSign', { width: 3.55, height: 0.42, depth: 0.18 }, 'plaque', ['left-plaque']),
  component('rightLongPlaque', 'rightLongPlaque', 'micro', 'rear plaque spanning from the raised-sign return to the right wall inner face', 'roofTrim', { width: 11.3, height: 0.48, depth: 0.2 }, 'plaque', ['right-plaque', 'wall-aligned-right-edge', 'front-logo-texture', 'contain-fit', 'horizontal-orientation']),
  component('rightLongPlaque-frontTexture', 'rightLongPlaque-frontTexture', 'micro', 'replaceable transparent front logo plane', 'rightLongPlaque', { width: 1.74, height: 0.393, depth: 0.01 }, 'plaque', ['front-logo-texture', 'preserve-aspect', 'no-mirror']),
  component('leftWindow', 'leftWindow', 'meso', 'side window frame', 'leftWall', { width: 0.3, height: 4.7, depth: 3.7 }, 'iron', ['left-window']),
  component('leftWindowTexturePanel', 'leftWindowTexturePanel', 'micro', 'replaceable light inset window panel', 'leftWindow', { width: 0.08, height: 4.5, depth: 3.35 }, 'wallSide', ['replaceable-window-texture', 'non-black-inset']),
  component('doorFrame', 'doorFrame', 'meso', 'door surround', 'rightWall', { width: 0.34, height: 10.0, depth: 3.8 }, 'woodLight', ['embedded-door']),
  component('door', 'door', 'meso', 'blue-violet hinged door matching wall thickness', 'rightWall', { width: 1, height: 9.45, depth: 3.15 }, 'door', ['embedded-door', 'door-thickness', 'round-handle']),
  component('wainscot', 'wainscot', 'meso', 'light warm-gray-brown wood-grain wall skirt on all three walls', 'roomShell', { width: 19.55, height: 4.5, depth: 0.12 }, 'wainscot', ['wood-grain-wainscot', 'wainscot-height']),
  component('rightLongPlaqueUnderline', 'rightLongPlaqueUnderline', 'micro', 'continuous brown underline below wall-aligned long plaque', 'roofTrim', { width: 11.3, height: 0.22, depth: 0.28 }, 'wood', ['plaque-underline', 'wall-aligned-right-edge']),
  component('doorSteps', 'doorSteps', 'micro', 'two checker steps', 'rightWall', { width: 2.9, height: 0.72, depth: 2.0 }, 'checker', ['checker-steps']),
];
const material = (id, name, color, roughness, metalness = 0, localOverrides = []) => ({ id, name, type: 'standard', shaderModel: 'MeshStandardMaterial', baseColor: color, color, albedo: { dominant: color, secondary: [color], samplingNotes: 'Reference-derived stylized palette.' }, colorVariation: { palette: [color], pattern: 'subtle', amplitude: 0.04, heightCorrelation: 0.1 }, textureResolution: 1024, roughness: { base: roughness, variation: 0.04, map: 'procedural-solid' }, metalness: { base: metalness, variation: 0.02 }, normal: { pattern: 'subtle surface response', strength: 0.08, scale: 18, space: 'tangent' }, bump: { pattern: 'micro breakup', amplitude: 0.01, scale: 18 }, displacement: { pattern: 'none', amplitude: 0, scale: 1, silhouetteAffects: false }, ambientOcclusion: { cavityStrength: 0.2, contactShadowBias: 0.25, notes: 'Contact at architectural joins.' }, localOverrides, referencePbr: { usable: true, confidence: 0.72, maps: { albedo: { path: 'procedural://room-shell/albedo' }, roughness: { path: 'procedural://room-shell/roughness' }, height: { path: 'procedural://room-shell/height' }, normal: { path: 'procedural://room-shell/normal' }, ao: { path: 'procedural://room-shell/ao' } } }, shaderNotes: ['Procedural lookdev; no hidden surface claim.'], textureProjection: { mode: 'uv', repeat: [1.2, 1.2], texelDensityIntent: 'stable miniature scale' }, surfaceFrequencyBands: [{ id: 'macro', frequency: 2, amplitude: 0.05, role: 'broad value' }, { id: 'meso', frequency: 12, amplitude: 0.025, role: 'edge variation' }, { id: 'micro', frequency: 48, amplitude: 0.01, role: 'highlight breakup' }] });
spec.materials = [material('wall', 'Warm cream wall', '#E8DFCF', 0.88, 0, [{ id: 'wall-contact', region: 'wall and base joins', roughness: 0.9 }]), material('wallSide', 'Side wall cream', '#DED4C2', 0.9), material('wood', 'Dark wood trim', '#63382C', 0.82, 0, [{ id: 'trim-edge', region: 'all bevels', roughness: 0.78 }]), material('woodLight', 'Light wood edge', '#9D6244', 0.82), material('wainscot', 'Light warm gray brown wainscot', '#A48670', 0.84, 0, [{ id: 'wainscot-accent', region: 'vertical and top/bottom rails', color: '#896B58', roughness: 0.84 }]), material('floor', 'Warm wood floor', '#B98762', 0.86), material('base', 'Deep warm base', '#4D3B3B', 0.86), material('door', 'Blue violet door', '#51418A', 0.78), material('iron', 'Soft dark metal', '#29252D', 0.45, 0.55), material('plaque', 'Warm plaque', '#9B6A32', 0.72), material('checker', 'Checker tile', '#F4EEE1', 0.9)];
spec.featureReviewTargets = [{ id: 'three-wall-silhouette', name: 'three-wall open silhouette', tier: 'critical', criteria: 'Rear, left and right walls remain connected at 90 degrees while the front and top stay open.', evidenceRefs: ['reference-groups'] }, { id: 'short-left-wall-opening', name: 'short left wall with opening', tier: 'critical', criteria: 'Left wall length is approximately 6.3 and its window is a clear opening with aligned inner and outer frames through the uniform 1.0 wall thickness.', evidenceRefs: ['reference-groups'] }, { id: 'flat-rear-top', name: 'flat rear top except raised sign', tier: 'critical', criteria: 'Rear wall body and continuous 1.0-depth top rail are level; only the enlarged left raised sign rises above it.', evidenceRefs: ['reference-groups'] }, { id: 'embedded-door', name: 'embedded door wall', tier: 'critical', criteria: 'Blue-violet 1.0-thick door is seated inside a real right-wall opening with transom, mullions, round gold handle and two checker steps.', evidenceRefs: ['reference-groups'] }, { id: 'wainscot-thickness', name: 'light warm-gray-brown wainscot and shell thickness', tier: 'important', criteria: 'All three interior walls have 4.5-high low-contrast wood-grain wainscot while wall side faces remain visible from oblique and top views.', evidenceRefs: ['reference-groups'] }];
spec.qualityContract.minimumSpecDepth = { macroComponents: 5, mesoComponents: 5, microFeatureGroups: 4, materialLayers: 4, repetitionSystems: 2, reviewViewpoints: 5 };
spec.qualityContract.featureGroups = spec.featureReviewTargets.map((x) => ({ id: x.id, name: x.name, required: x.tier === 'critical', qualityCriteria: [x.criteria], evidenceRefs: x.evidenceRefs, failureModes: ['feature missing, disconnected or occluded'] }));
spec.repetitionSystems = [{ id: 'roof-rail', componentRef: 'roofTrim', count: 1, distribution: 'continuous flat rail along rear wall', spacing: 'full 20.15 width' }, { id: 'wainscot-boards', componentRef: 'wainscot', count: 3, distribution: 'back/left/right wall interior sections', spacing: 'wall-specific segmented runs' }, { id: 'checker-steps', componentRef: 'doorSteps', count: 2, distribution: 'stacked front of door', spacing: '0.62 depth pitch' }];
spec.lightingFromPhoto = [{ id: 'key', type: 'soft directional', color: '#FFF0D7', intensity: 2.2, direction: 'upper front-left', shadow: 'soft contact' }, { id: 'fill', type: 'hemisphere environment', color: '#F7F5EF', intensity: 1.8, direction: 'broad front', shadow: 'low contrast' }, { id: 'rim', type: 'soft rim', color: '#DDE9FF', intensity: 0.45, direction: 'rear edge', shadow: 'ground shadow; exposure 1.12 ACESFilmicToneMapping' }];
spec.qualityTargets = { reviewViewpoints: ['front', 'left', 'right', 'top', 'rear'] };
spec.lookDevTargets = { silhouette: 'open three-wall miniature shell with asymmetric stepped base', colorPalette: ['#E8DFCF', '#63382C', '#51418A', '#B98762'], materials: ['matte plaster', 'wood trim', 'painted door', 'soft metal'], lighting: 'soft warm key with neutral hemisphere fill', exposure: 1.12, toneMapping: 'ACESFilmicToneMapping', contactShadows: true };
spec.proceduralStrategy = ['Use Shape + ExtrudeGeometry for base and rear wall solids.', 'Use four segmented side-wall extrusions to form the true left window opening and three segmented right-wall door opening.', 'Use RoundedBoxGeometry for continuous roof rail, wainscot boards, frames, plaques and checker tiles.', 'Keep every architectural part under one roomShell root with stable IDs and replaceable plaque/window texture paths.'];
spec.performanceBudget = { qualityPriority: 'reference-fidelity', targetTriangles: 60000, maxDrawCalls: 120, textureSize: 1024, fpsTarget: 30, optimizationPolicy: 'Keep architectural silhouette and openings; simplify only repeated trim and checker tiles at distance.' };
spec.actionReadiness = { objectRoot: 'roomShell', interactionMode: 'whole-object', movableComponents: ['leftRaisedSign', 'signWindow', 'leftPlaque', 'rightLongPlaque', 'door'], stablePivots: true, notes: 'Independent named children support later replacement or animation.' };
 spec.extensions = { ...(spec.extensions || {}), roomShellCalibration: { wallThickness: 1, doorThickness: 1, wainscotHeight: 4.5, wainscotColor: '#A48670', wainscotAccent: '#896B58', wainscotRoughness: 0.84, leftWainscotWindowBay: { zStart: -4.92, zEnd: -1.85, height: 4.5 }, rightWainscotSegments: [{ zStart: -6.15, zEnd: 0.975 }, { zStart: 4.125, zEnd: 6.45 }], rightLongPlaqueSpan: { left: -2.3, right: 9.0, alignedTo: 'rightWall.innerFace' }, rightLongPlaqueWidth: 11.3, rightLongPlaqueUnderlineWidth: 11.3, rightLongPlaqueFrontTexture: { path: 'assets/signs/right-long-plaque-logo-transparent.png', fit: 'contain', orientation: 'horizontal', preserveAspect: true, transparentBackground: true, fallback: 'original plaque material' }, signWindowFrontTexture: { path: 'assets/signs/left-plaque-logo-transparent.png', fit: 'contain', orientation: 'horizontal', preserveAspect: true, transparentBackground: true, fallback: 'dark sign background', background: '#263038', crossDecorationsVisible: false }, signWindowIronVVisible: false, signWindowIronHVisible: false, leftWindowInnerFrame: true, leftWindowOuterFrame: true, leftWindowTexturePanel: { replaceableTexture: 'assets/windows/left-window-panel.png', visible: true }, signWindowVerticalAdjustment: -0.225, signWindowCenteredInRaisedPanel: true, leftPlaqueVisible: false, doorFrameVisible: false, rightLongPlaqueUnderlineVisible: false, floorPattern: 'subtle-light-vertical-seams-and-staggered-horizontal-joints', doorHandleShape: 'sphere' } };
fs.writeFileSync(file, JSON.stringify(spec, null, 2) + '\n');
