import fs from 'node:fs';
const path = new URL('./object-sculpt-spec.json', import.meta.url);
const s = JSON.parse(fs.readFileSync(path,'utf8'));
const img='C:/Users/ZYB/Desktop/reference/guizi.png'; const ev=['full-object','front-view','left-view','top-view','rear-view'];
s.targetName='Detective Lodge Archive Cabinet'; s.targetId='archive-cabinet'; s.coordinateFrame={front:'+Z',up:'+Y',lateral:'+X',origin:'cabinet bottom center',scaleReference:'world units match 9.0 W x 4.0 D x 12.3 H cm reference'};
s.preSpecAssessment.objectClass={primaryType:'archive cabinet',primaryDomain:'object',formLanguage:['stylized miniature','rounded bevels','toy-model furniture'],structureKind:['tall carcass','open shelf bays','eight drawer grid','full rear panel'],motionPotential:['static prop','drawers future optional animation'],materialFamilies:['matte yellow-green painted wood','paper','book cloth','woven fiber','low-metal hardware'],notes:'Composite four-view measurement sheet; rear joinery and drawer runners are approximate.'};
s.preSpecAssessment.complexity={tier:'complex',scores:{silhouetteComplexity:3,componentCount:3,hierarchyDepth:3,repetitionDensity:3,materialLayerCount:3,localDetailDensity:3,occlusionRisk:3,actionReadinessNeed:3},estimatedCounts:{macroComponents:8,mesoComponents:18,microFeatureGroups:7,materialLayers:5,repetitionSystems:2},reasoning:['Tall carcass, three shelf bays, eight drawers, repeated books and hardware require a deep assembled hierarchy.']};
const detail=(id,kind,ref,feature,confidence=.85)=>({id,kind,mapsTo:{ref},zone:ref,feature,evidenceRefs:ev,confidence});
s.preSpecAssessment.detailInventory={scanMethod:'component-zones',targetMinDetails:14,details:[
 detail('cabinet-bevel','bevel','cabinetBody','rounded outer carcass edges'),detail('top-cap','contour','cabinetTop','thick top cap overhang'),detail('shelf-thickness','ridge','shelfTop','three connected shelf boards'),detail('certificate-frames','contour','certificateRow','three framed certificates'),detail('upper-books','contour','bookRowUpper','varied dark book spines'),detail('woven-boxes','stain','fileRowMiddle','two tan woven archive boxes'),detail('lower-books','contour','bookRowLower','mixed light and dark lower books'),detail('newspaper-fold','contour','newspaper','draped folded newspaper'),detail('drawer-grid','seam','drawerRows','two rows of four inset drawers'),detail('drawer-handles','fastener','drawerHandles','eight independent handles'),detail('drawer-fasteners','fastener','drawerRows','small corner fasteners'),detail('cabinet-feet','ridge','cabinetFeet','short stepped feet'),detail('back-panel','contour','cabinetBack','complete rear panel'),detail('material-variation','stain','cabinetBody','subtle yellow-green value variation') ]};
s.silhouette={boundingShape:'tall rectangular cabinet with cap, plinth, and slightly recessed front contents',aspectRatios:['width:height 0.732','width:depth 2.25'],symmetry:'near bilateral symmetry with varied replaceable contents',dominantCurves:['soft bevels on carcass and drawer fronts'],negativeSpaces:['three open shelf bays','drawer reveals'],landmarks:['top y=12.3','drawer grid y=0.55-3.1','shelf planes y=3.65,6.35,9.05']};
s.viewEvidence=[{id:'full-object',view:'composite-sheet',imageRegion:{x:0,y:0,width:1,height:1,units:'normalized'},observations:['front,left,top,rear orthographic views with dimensions'],confidence:.92},{id:'front-view',view:'front',imageRegion:{x:0,y:0,width:.52,height:.52,units:'normalized'},observations:['cabinet proportions, shelves, eight drawers and contents'],confidence:.95},{id:'left-view',view:'left',imageRegion:{x:.52,y:0,width:.48,height:.52,units:'normalized'},observations:['depth 4.0, side panel thickness and cap'],confidence:.9},{id:'top-view',view:'top',imageRegion:{x:0,y:.52,width:.52,height:.48,units:'normalized'},observations:['rectangular footprint and top overhang'],confidence:.85},{id:'rear-view',view:'rear',imageRegion:{x:.52,y:.52,width:.48,height:.48,units:'normalized'},observations:['full rear backboard and feet'],confidence:.9}];
const action=(role='static')=>({animationRole:role,pivot:{mode:'local-origin',localPosition:[0,0,0],axis:[0,1,0],confidence:.8},transformChannels:{translate:true,rotate:true,scale:true,bend:false,twist:false,detach:false,visibility:true,materialState:true},sockets:[],collider:{type:'box',offset:[0,0,0],scale:[1,1,1],isTrigger:false,notes:'simplified runtime proxy'},constraints:[],destruction:{breakable:false,fractureGroup:role,seamRefs:[],detachableFragments:[],breakImpulse:0,debrisMaterial:'cabinet'}});
const comp=(id,name,level,parent,dim,pos,material='cabinet',features=[])=>({id,name,level,role:'cabinet component',importance:level==='macro'?1:.75,confidence:.86,primitive:'box',topologyClass:'assembled-solid',topologyRationale:'Separate beveled solid part or replaceable content group.',geometryDescriptor:{topologyIntent:'rounded assembled furniture part',edgeTreatment:{type:'bevel',bevelRadius:level==='micro'?.025:.09,segments:level==='micro'?3:5},deformationStack:[],uvStrategy:'generated procedural coordinates',normalStrategy:'vertex normals from generated geometry'},parent,attachment:parent?{parentSocket:'mount-'+parent,localStart:[0,0,0],localEnd:[0,0,0],contactType:'overlap',embedDepth:.03,gapTolerance:.02}:null,dimensions:{width:dim[0],height:dim[1],depth:dim[2],units:'world',confidence:.9},transform:{position:pos,rotation:[0,0,0],scale:[1,1,1]},actionProfile:action(id==='archiveCabinet'?'root':id),material,materialLayers:[material],deformations:[],joints:[],seams:[],localFeatures:features.map(f=>({id:f,description:f,evidenceRefs:ev})),surfaceDetail:{macroRoughness:.08,microRoughness:.04,bumpAmplitude:.01,normalPattern:'subtle painted grain',displacementPattern:'none',occlusionPattern:'shelf and drawer cavities',edgeWearPattern:'bevel highlight',notes:'Stylized miniature response'},evidenceRefs:ev,details:features,fidelityTier:'form-refinement',colorMaterialRecipe:{dominantAlbedo:'rgba(205,197,92,1)',secondaryAlbedo:'rgba(231,221,126,1)',materialClass:material==='metal'?'metal':'wood',materialClassConfidence:.9,evidenceRefs:ev}});
const p=[]; p.push(comp('archiveCabinet','archiveCabinet','macro',null,[9,12.3,4],[0,0,0],'cabinet',['cabinet silhouette','full rear panel']));
p.push(comp('cabinetBody','cabinet body','macro','archiveCabinet',[8.2,11.55,3.7],[0,.55,0],'cabinet',['side panels','interior cavity'])); p.push(comp('cabinetTop','cabinet top','macro','archiveCabinet',[9.2,.45,4.1],[0,12.075,0],'cabinet',['top cap overhang'])); p.push(comp('cabinetBack','cabinet back','macro','archiveCabinet',[8.3,11.3,.24],[0,6.2,-1.88],'back',['complete rear backboard'])); p.push(comp('shelfSystem','shelf system','macro','archiveCabinet',[8.25,5.9,3.65],[0,6.2,0],'shelf',['three connected shelf planes'])); p.push(comp('drawerUnit','drawer unit','macro','archiveCabinet',[8.35,3.1,3.75],[0,1.9,0],'drawer',['two rows of four drawers'])); p.push(comp('contentSystem','replaceable content system','macro','archiveCabinet',[8.0,7.0,3.8],[0,8.0,.1],'content',['certificates','books','boxes','newspaper'])); p.push(comp('cabinetFeet','cabinet feet','macro','archiveCabinet',[8.4,.45,3.9],[0,.22,0],'cabinet',['short plinth feet']));
for(const id of ['shelfTop','shelfMiddle','shelfBottom']) p.push(comp(id,id,'meso','shelfSystem',[8.15,.28,3.65],[0,id==='shelfTop'?9.05:id==='shelfMiddle'?6.35:3.65,0],'shelf',['thick shelf board','side connection']));
p.push(comp('certificateRow','certificate row','meso','contentSystem',[7.6,1.9,3.6],[0,10.005,1.55],'paper',['three framed certificates','shelf contact'])); p.push(comp('bookRowUpper','upper book row','meso','contentSystem',[3.0,1.9,2.7],[-2.35,7.43,.42],'book',['varied dark spines','full book depth'])); p.push(comp('fileRowMiddle','middle file row','meso','contentSystem',[7.2,1.75,3.05],[0,7.355,.25],'content',['two woven boxes','full box depth','shelf contact'])); p.push(comp('bookRowLower','lower book row','meso','contentSystem',[7.4,1.9,2.72],[0,4.71,.42],'book',['mixed books and files','full book depth'])); p.push(comp('drawerRows','drawer rows','meso','drawerUnit',[8.0,2.6,3.15],[0,2.05,.35],'drawer',['eight full-depth inset drawers','stacked contact'])); p.push(comp('drawerHandles','drawer handles','meso','drawerUnit',[7.8,2.6,.3],[0,2.05,2.08],'metal',['eight independent handles'])); p.push(comp('newspaper','newspaper','meso','bookRowLower',[2.5,.2,1.15],[0,5.62,1.7],'paper',['draped fold','replaceable texture','supported contact']));
for(let i=0;i<8;i++){const col=i%4,row=Math.floor(i/4),y=1.35+row*1.40; p.push(comp(`drawer${i+1}`,`drawer ${i+1}`,'micro','drawerRows',[1.9,1.2,3.15],[-3.0+col*2.0,y,.35],'drawer',['drawer seam','pull socket','full drawer depth'])); p.push(comp(`drawerHandle${i+1}`,`drawer handle ${i+1}`,'micro','drawerHandles',[.7,.16,.12],[-3.0+col*2.0,y,2.08],'metal',['rounded handle','fastener pair'])); }
for(let i=0;i<10;i++) p.push(comp(`book${i+1}`,`book ${i+1}`,'micro',i<5?'bookRowUpper':'bookRowLower',[.45+(i%3)*.12,1.35+(i%4)*.12,2.7],[i<5?-3.45+(i%5)*.75:-3.45+(i%5)*.72, i<5?7.43:4.71,.42], 'book',['spine color variation','full book depth']));
s.componentTree=p; const refs=['cabinet-bevel','top-cap','shelf-thickness','certificate-frames','upper-books','woven-boxes','lower-books','newspaper-fold','drawer-grid','drawer-handles','drawer-fasteners','cabinet-feet','back-panel','material-variation']; for(const r of refs) p[0].localFeatures.push({id:r,description:r,evidenceRefs:ev});
s.featureReviewTargets=[{id:'cabinet-proportion',name:'Tall cabinet proportions',tier:'critical',passIds:['blockout'],minimumScore:.8,mustPass:true,componentRefs:['archiveCabinet','cabinetBody','cabinetTop'],evidenceRefs:ev},{id:'shelf-content',name:'Three shelf bays and replaceable contents',tier:'critical',passIds:['structural-pass','form-refinement'],minimumScore:.8,mustPass:true,componentRefs:['shelfSystem','certificateRow','fileRowMiddle','bookRowLower'],evidenceRefs:['front-view']},{id:'drawer-grid',name:'Two rows of four inset drawers',tier:'critical',passIds:['structural-pass','form-refinement'],minimumScore:.8,mustPass:true,componentRefs:['drawerUnit','drawerRows'],evidenceRefs:['front-view']},{id:'rear-panel',name:'Complete rear panel and side depth',tier:'important',passIds:['structural-pass'],minimumScore:.65,mustPass:false,componentRefs:['cabinetBack'],evidenceRefs:['left-view','rear-view']},{id:'cabinet-finish',name:'Yellow-green matte cabinet finish',tier:'important',passIds:['material-pass'],minimumScore:.65,mustPass:false,componentRefs:['cabinetBody'],evidenceRefs:ev}];
const pbr=(id,color,rough=.8,metal=0)=>({id,name:id,type:'standard',shaderModel:'MeshStandardMaterial',baseColor:color,color,albedo:{dominant:color,secondary:[color],samplingNotes:'inferred from guizi.png'},colorVariation:{palette:[color],pattern:'subtle value variation',amplitude:.08,heightCorrelation:.2},textureResolution:1024,textureProjection:{mode:'procedural-uv',repeat:[1.5,1.5],anisotropy:4,texelDensityIntent:'object scale'},surfaceFrequencyBands:[{id:'macro',frequency:1,amplitude:.06,role:'broad value'},{id:'meso',frequency:8,amplitude:.025,role:'soft grain'},{id:'micro',frequency:32,amplitude:.01,role:'highlight breakup'}],roughness:{base:rough,variation:.08,map:'independent-procedural-field',localResponse:'bevel highlights'},metalness:{base:metal,variation:.03},normal:{pattern:'independent subtle grain',strength:.12,scale:18,space:'tangent'},bump:{pattern:'fine grain',amplitude:.008,scale:1},displacement:{pattern:'none',amplitude:0,scale:1,silhouetteAffects:false},ambientOcclusion:{cavityStrength:.22,contactShadowBias:.25,notes:'drawer and shelf recesses'},wear:{edgeWear:.03,scratches:[],chips:[]},dirt:{amount:.02,cavityBias:.3,color:'#5d5332'},localOverrides:[{id:'bevel-highlight',region:'bevels',effect:'lighter edge',evidenceRefs:ev}],referencePbr:{version:'1.0',sourceImage:img,extractor:'procedural-inference',method:'stylized palette inference',verdict:'usable-for-stylized-preview',hardLimit:'composite sheet; no exact texture crop',usable:true,confidence:.72,estimatedFidelity:.72,targetThreshold:.7,maps:{albedo:{path:img},roughness:{path:img},height:{path:img},normal:{path:img},ao:{path:img}}},notes:'Procedural approximation; replaceable content textures.'});
s.materials=[pbr('cabinet','#CDC55C',.82,0),pbr('shelf','#B7B05A',.84,0),pbr('book','#31434A',.86,0),pbr('paper','#EEE5CE',.9,0),pbr('metal','#8C8A7D',.34,.55),pbr('back','#9B8D5A',.88,0),pbr('drawer','#C9A255',.8,0),pbr('content','#D0B783',.88,0)]; s.repetitionSystems=[{id:'drawer-grid',name:'8 drawer fronts',componentRefs:Array.from({length:8},(_,i)=>`drawer${i+1}`),count:8,distribution:'two rows of four mirrored grid',spacing:{x:2,y:1.45,z:0},seed:11,instancing:'shared beveled drawer geometry',evidenceRefs:['front-view']},{id:'book-spines',name:'varied replaceable books',componentRefs:Array.from({length:10},(_,i)=>`book${i+1}`),count:10,distribution:'upper and lower shelf rows with varied widths and colors',spacing:{x:.72,y:0,z:0},seed:23,instancing:'shared low-poly book geometry',evidenceRefs:['front-view']}];
s.lightingFromPhoto=[{id:'key',type:'area',color:'#FFF2D7',intensity:2.4,position:[7,14,10],size:6,role:'soft key; exposure 1.0; ACES tone mapping; contact shadow'},{id:'fill',type:'hemisphere',color:'#DCEBFF',intensity:1.2,position:[-6,8,-6],role:'cool fill; ambient occlusion contact shadow'},{id:'rim',type:'directional',color:'#FFFFFF',intensity:.65,position:[-4,10,-8],role:'edge separation; ground shadow'}];
s.lookDevTargets.lightingPass={keyLight:'large warm area',fillLight:'cool hemisphere',rimLight:'soft white rear directional',exposure:1.0,toneMapping:'ACESFilmicToneMapping',background:'#F7F5EF',contactShadow:'soft PCF shadow map'};
s.assumptions=['Back panel is modeled as a continuous board; fasteners and drawer runners are approximate.','Reference content is simplified and remains replaceable; exact text/labels are not inferred.','Dimensions use world units equal to the annotated centimeters.']; s.risks=['Composite sheet is fragmented for single-silhouette pixel gates.','Procedural wood, books, weave, and paper are stylized approximations.']; s.performanceBudget.targetTriangles=70000; s.performanceBudget.maxDrawCalls=140;
fs.writeFileSync(path,JSON.stringify(s,null,2)); console.log(`wrote ${p.length} components`);
